name: Testing and Quality

on:
  pull_request:

jobs:
  test:
    runs-on: codeberg-small-lazy

    container:
      image: archlinux:latest

    steps:
      - name: Install base tools
        run: pacman -Syu --noconfirm git nodejs npm gcc clang make cmake

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: compile
        working-directory: bootstrap
        run: make -f GNUmake -j 2

      - name: Run
        working-directory: bootstrap
        run: ./bin/traceyc index.trc -o app -Wall
