matrix:
  include:
    - COMPILER: gcc
      CC: gcc
      ARCH: x86_64
    - COMPILER: clang
      CC: clang
      ARCH: x86_64

when:
  - event: pull_request

steps:
  - name: ${COMPILER}-${ARCH}
    image: archlinux:latest
    directory: bootstrap
    environment:
      CC: ${CC}
      ARCH: ${ARCH}
    commands:
      - pacman-key --init
      - pacman -Syu --noconfirm ${COMPILER} make automake libtool autoconf
      - autoreconf -fi
      - mkdir -p build && cd build
      - ../configure
      - make V=1
      - .traceyc ../index.trc -o app -Wall
